name: Generate docs

on:
  push:
    branches:
      - main

jobs:
  build-pages:
    name: Rebuild and deploy docs on version bump
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'bump:')"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install packages
        run: npm install
      - name: Build
        run: npm run build-storybook
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./docs
